name: Master Release
on:
  push:
    branches:
      - "master"

jobs:
  go-build:
    # 设置默认run选项
    defaults:
      run:
        shell: bash
        # working-directory: scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.19"
      - shell: bash
        run: |
          go mod tidy
          go build  -ldflags "-s -w" -o date-go  date.go
  go-test:
    defaults:
      run:
        shell: bash
        # working-directory: scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.19"
      - shell: bash
        run: |
          set -ex
          go test -v
  notify-message:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    if: ${{ failure() || success() || cancelled() }} # failure()  always()  cancelled()  success()
    steps:
      - run: |
          set -ex
          curl 'https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxx' \
          -H 'Content-Type: application/json' \
          -d '{"msgtype": "text","text": {"content":"我就是我, 是不一样的烟火"}}'
  release-package:
    defaults:
      run:
        shell: bash
