apiVersion: siri-test.my.domain/v1
kind: AppService
metadata:
  labels:
    app.kubernetes.io/name: appservice
    app.kubernetes.io/instance: appservice-sample
    app.kubernetes.io/part-of: kubebuilderdemo
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebuilderdemo
  name: appservice-sample
spec:
  # TODO(user): Add fields here
  routes:
  - domain: "siritest"
    path: "/"
  image: "docker.io/sirius/demo"
  service:
    sourcePort: 80
    targetPort: 80
  ingress: true